---
pages:
- music.md
- store.md
- press.md
- _index.md
- download.md
- about-us.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: type
  label: Type
  type: text
  hidden: true
  default: ''
- name: image
  label: Image
  type: file
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: datetime
  name: date
  label: Date
  hidden: false
