---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: type
  label: Type
  type: text
  hidden: true
  default: ''
- name: image
  label: Image
  type: file
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: datetime
  name: date
  label: Date
  hidden: false
pages:
- hugo/content/store.md
- hugo/content/press.md
- hugo/content/_index.md
- hugo/content/download.md
- hugo/content/about-us.md
