---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
upload_dir: hugo/static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.31.1
