---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
upload_dir: hugo/static/img
public_path: "/img"
front_matter_path: "/img"
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.31.1
  - BUILD_DIR=hugo
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.31.1
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.31.1
